#if !canImport(ObjectiveC)
  import XCTest

  extension AnalyticsHitParserMessageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnalyticsHitParserMessageTests = [
      ("testEquality", testEquality)
    ]
  }

  extension AnalyticsHitTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnalyticsHitTypeTests = [
      ("testValues", testValues)
    ]
  }

  extension AnalyticsParameterEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnalyticsParameterEncoderTests = [
      ("testEncode", testEncode)
    ]
  }

  extension AnalyticsRequestBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnalyticsRequestBuilderTests = [
      ("testInitDefault", testInitDefault),
      ("testInitwParams", testInitwParams),
      ("testRequest", testRequest)
    ]
  }

  extension AnalyticsResultDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnalyticsResultDecoderTests = [
      ("testDebugFailure", testDebugFailure),
      ("testDebugSuccess", testDebugSuccess),
      ("testReleaseFailure", testReleaseFailure),
      ("testReleaseSuccess", testReleaseSuccess)
    ]
  }

  extension AnalyticsSessionManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnalyticsSessionManagerTests = [
      ("testBuilderErrorSend", testBuilderErrorSend),
      ("testInit", testInit),
      ("testSessionErrorSend", testSessionErrorSend)
    ]
  }

  extension AnalyticsTrackerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnalyticsTrackerTests = [
      ("testCustomTrackable", testCustomTrackable),
      ("testError", testError),
      ("testEvent", testEvent),
      ("testException", testException),
      ("testInit", testInit),
      ("testInitDebugMode", testInitDebugMode),
      ("testTime", testTime)
    ]
  }

  extension AnalyticsURLSessionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnalyticsURLSessionTests = [
      ("testInit", testInit)
    ]
  }

  extension AnalyticsURLsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnalyticsURLsTests = [
      ("testURLs", testURLs)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(AnalyticsHitParserMessageTests.__allTests__AnalyticsHitParserMessageTests),
      testCase(AnalyticsHitTypeTests.__allTests__AnalyticsHitTypeTests),
      testCase(AnalyticsParameterEncoderTests.__allTests__AnalyticsParameterEncoderTests),
      testCase(AnalyticsRequestBuilderTests.__allTests__AnalyticsRequestBuilderTests),
      testCase(AnalyticsResultDecoderTests.__allTests__AnalyticsResultDecoderTests),
      testCase(AnalyticsSessionManagerTests.__allTests__AnalyticsSessionManagerTests),
      testCase(AnalyticsTrackerTests.__allTests__AnalyticsTrackerTests),
      testCase(AnalyticsURLSessionTests.__allTests__AnalyticsURLSessionTests),
      testCase(AnalyticsURLsTests.__allTests__AnalyticsURLsTests)
    ]
  }
#endif
